"""Shell HTML de AutoScrum Control Tower."""
from sdd.presentation.web_script import SCRIPT
from sdd.presentation.web_styles import CSS

PAGE = r"""<!doctype html><html lang="es"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light">
<title>AutoScrum · Control Tower</title><style>""" + CSS + r"""</style></head><body>
<div class="shell">
 <aside class="sidebar" id="sidebar">
  <div class="brand"><div class="brand-mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 7.5 12 3l7 4.5v9L12 21l-7-4.5z"/><path d="m8.5 9.5 3.5-2 3.5 2v5L12 17l-3.5-2.5z"/></svg></div><div class="brand-copy"><b>AutoScrum</b><span>Control Tower</span></div></div>
  <div class="nav-label">Operación</div>
  <button class="nav-btn active" data-view="workspace"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M4 5h6v6H4zM14 5h6v4h-6zM14 13h6v6h-6zM4 15h6v4H4z"/></svg><span>Vista en vivo</span><small class="nav-badge" id="nav-active">0</small></button>
  <button class="nav-btn" data-view="history" data-tab=tasks><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></svg><span>Historial</span></button>
  <button class="nav-btn" data-view="results"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M4 4h16v16H4zM8 9h8M8 13h8M8 17h5"/></svg><span>Resultados</span></button>
  <div class="nav-label">Sistema</div>
  <button class="nav-btn" data-view="settings"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.6-1.4.9-1.9-2.1-2.1-1.9.9-1.4-.6L11.2 3h-3l-.7 2-1.4.6-1.9-.9-2.1 2.1.9 1.9-.6 1.4-2 .7v3l2 .7.6 1.4-.9 1.9 2.1 2.1 1.9-.9 1.4.6.7 2h3l.7-2 1.4-.6 1.9.9 2.1-2.1-.9-1.9.6-1.4z"/></svg><span>Configuración</span></button>
  <div class="sidebar-foot"><div class="connection" id="connection"><i></i><span>Conectando al runtime</span></div></div>
 </aside>
 <header class="topbar"><button class="icon-btn mobile-menu" id="mobile-menu" aria-label="Abrir menú">☰</button><div class="crumbs"><b id="crumb-title">Vista en vivo</b><span id="crumb-sub">Sin ejecución seleccionada</span></div><div class="top-spacer"></div>
  <div class="metric-chip"><div class="metric-icon">◎</div><div><span>Agentes</span><b id="metric-agents">0 activos</b></div></div>
  <div class="metric-chip"><div class="metric-icon">◈</div><div><span>Tokens</span><b id="metric-tokens">0</b></div></div>
  <div class="run-state" id="run-state"><i></i><span>En reposo</span></div>
 </header>
 <main class="content">
  <section class="view" id="view-workspace">
   <div class="workspace-layout">
    <div class="workspace-canvas"><div class="workspace-head"><div><h1>Equipo en vivo</h1><p>Sigue el trabajo, las decisiones y los traspasos del sistema en un solo lugar.</p></div><button class="primary-btn" id="new-run">Nueva ejecución</button></div>
     <section class="failure-alert hidden" id="failure-alert" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="failure-signal" aria-hidden="true">!</div><div class="failure-copy"><span class="eyebrow" id="failure-kicker">Proceso bloqueado</span><h2 id="failure-title">La ejecución necesita atención</h2><p id="failure-reason"></p><p class="failure-impact" id="failure-impact"></p><div class="failure-meta" id="failure-meta"></div><ul id="failure-findings"></ul><div class="failure-action" id="failure-action"></div><details class="failure-technical" id="failure-technical"><summary>Ver detalles técnicos</summary><div id="failure-technical-meta"></div><ul id="failure-technical-findings"></ul></details></div>
       <div class="failure-actions"><div class="human-review hidden" id="human-review"><b>Evaluación pendiente</b><pre id="review-evaluation"></pre><label for="review-feedback">Feedback para rechazar</label><textarea id="review-feedback" placeholder="Describe qué debe corregir el agente"></textarea><div><button class="primary-btn" id="accept-review">Aceptar</button><button class="danger-btn" id="reject-review">Rechazar</button></div></div><button class="primary-btn" id="resume-failure">Continuar desde el fallo</button><button class="ghost-btn" id="replay-alert">Repetir alerta sonora</button></div>
     </section>
     <div class="canvas-panel active" id="canvas-operations">
      <section class="operations-stage" aria-label="Actividad del equipo en vivo">
       <header class="operations-head"><div><div class="live-caption"><i></i><span id="operations-live-label">Canal operativo conectado</span></div><p>La sala concentra el estado de cada agente y la conversación completa del workflow.</p></div><div class="operations-stats" aria-label="Resumen de actividad"><div><span>Activos</span><b id="ops-active">0</b></div><div><span>Decisiones</span><b id="ops-decisions">0</b></div><div><span>Delegaciones</span><b id="ops-delegations">0</b></div><div><span>Conversaciones</span><b id="ops-conversations">0</b></div></div></header>
       <div class="operations-grid">
        <section class="team-network-panel" aria-labelledby="team-network-title"><div class="operations-section-head"><div><h3 id="team-network-title">Quién está haciendo qué</h3><p>Selecciona un miembro para abrir su traza.</p></div><span class="network-legend"><i></i> vínculo activo</span></div><div class="team-network" id="team-network"><svg id="team-network-links" aria-hidden="true"></svg><button class="team-director" id="team-director" type="button" aria-label="Orquestador, director del sistema"><span class="director-mark"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 3v5m0 8v5M3 12h5m8 0h5"/><circle cx="12" cy="12" r="4"/></svg></span><b>Orquestador</b><small id="team-director-state">En espera</small></button></div><div class="handoff-strip" id="handoff-strip"><span>Sin delegaciones activas</span></div></section>
        <section class="team-feed-panel" aria-labelledby="team-feed-title"><div class="operations-section-head feed-heading"><div><h3 id="team-feed-title">Conversación del equipo</h3><p>Entradas, salidas y razones de cada cambio.</p></div><button class="feed-pause" id="pause-events" type="button" aria-pressed="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg><span>Pausar</span></button></div><div class="feed-toolbar"><div class="feed-filters" id="feed-filters" role="tablist" aria-label="Filtrar eventos"><button class="active" type="button" data-feed-filter="all" role="tab" aria-selected="true">Todo</button><button type="button" data-feed-filter="decision" role="tab" aria-selected="false">Decisiones</button><button type="button" data-feed-filter="delegation" role="tab" aria-selected="false">Delegaciones</button><button type="button" data-feed-filter="conversation" role="tab" aria-selected="false">Conversaciones</button><button type="button" data-feed-filter="io" role="tab" aria-selected="false">E/S</button><button type="button" data-feed-filter="gate" role="tab" aria-selected="false">Gates</button></div><label class="follow-toggle" for="follow-events"><input id="follow-events" type="checkbox" checked><span>Seguir actividad</span></label></div><div class="team-feed" id="team-feed" aria-live="polite" aria-relevant="additions text"><div class="feed-empty"><b>Esperando actividad</b><span>Los mensajes del equipo aparecerán al iniciar una ejecución.</span></div></div></section>
       </div>
      </section>
     </div>
    </div>
   </div>
  </section>
  <section class="view hidden" id="view-history"><div class="history-page"><div class="settings-head"><div><span class="eyebrow">Ejecuciones persistidas</span><h1>Historial</h1></div><button class="ghost-btn" id="refresh-history">Actualizar</button></div><div class="history-controls"><div class="field"><label for="history-project">Proyecto</label><select id="history-project"></select></div></div><div class="task-grid" id="history-tasks"></div></div></section>
  <section class="view hidden" id="view-results"><div class="history-page"><div class="settings-head"><div><span class="eyebrow">Entregables</span><h1>Resultados</h1></div></div><div class="results-grid" id="global-results"></div></div></section>
  <section class="view hidden" id="view-settings"><div class="settings-page"><div class="settings-head"><div><span class="eyebrow">Gobierno del sistema</span><h1>Configuración</h1></div></div><div class="settings-shell">
    <div class="settings-tabs" id="settings-tabs"><button data-settings="general">General</button><button data-settings="providers">Proveedores</button><button class="active" data-settings="agents">Agentes</button><button data-settings="runtime">Runtime</button><button data-settings="security">Seguridad</button></div>
    <div class="settings-tab-panel" id="settings-general"><div class="settings-form"><div class="field"><label for="output-base">Ruta base de salida</label><input id="output-base" placeholder="project"></div><div class="field"><label for="theme">Tema</label><select id="theme"><option value="auto">Automático</option><option value="dark">Oscuro</option><option value="light">Claro</option></select></div><div class="form-actions"><button class="primary-btn" id="save-general">Guardar cambios</button><span class="save-state" id="saved-general">Guardado</span></div></div></div>
    <div class="settings-tab-panel" id="settings-providers"><div class="settings-form"><div class="form-row"><div class="field"><label for="provider">Proveedor predeterminado</label><select id="provider"><option value="anthropic">Anthropic</option><option value="deepseek">DeepSeek</option><option value="qwen">Qwen</option><option value="glm">GLM</option><option value="kimi">Kimi</option><option value="openai">OpenAI-compatible</option></select></div><div class="field"><label for="provider-model">Modelo</label><select id="provider-model"></select></div></div><div class="field"><label for="provider-key">API key del proveedor</label><input id="provider-key" type="password" autocomplete="off" placeholder="••••••••••••"></div><div class="form-actions"><button class="primary-btn" id="save-provider">Guardar proveedor</button><button class="ghost-btn" id="toggle-key">Mostrar key</button><span class="save-state" id="saved-provider">Guardado</span></div></div></div>
    <div class="settings-tab-panel active" id="settings-agents"><section class="routing-policy"><div class="routing-head"><div><span class="eyebrow">Enrutamiento adaptativo</span><h3>Política de modelos</h3></div><div class="form-actions"><button class="ghost-btn" id="discover-models">Descubrir modelos</button><button class="primary-btn" id="save-routing">Guardar política</button></div></div><div class="routing-controls"><div class="field"><label for="routing-mode">Modo</label><select id="routing-mode"><option value="adaptive">Automático por política</option><option value="manual">Manual</option></select></div><div class="field"><label for="review-provider">Revisión R1/R2</label><select id="review-provider"><option value="">Proveedor automático</option><option value="anthropic">Anthropic</option><option value="openai">OpenAI</option><option value="glm">GLM</option><option value="kimi">Kimi</option><option value="deepseek">DeepSeek</option><option value="qwen">Qwen</option></select></div><div class="field"><label for="review-model">Modelo revisor</label><input id="review-model" placeholder="Automático frontier"></div><label class="tool-option routing-check"><input id="review-diversity" type="checkbox">Preferir proveedor distinto</label></div><div class="routing-preview" id="routing-preview"></div></section><div class="agent-settings"><aside class="agent-registry"><div class="registry-toolbar"><input id="agent-search" placeholder="Buscar agente…"><button class="icon-btn" id="import-agents" title="Importar configuración">⇧</button><button class="icon-btn" id="export-agents" title="Exportar configuración">⇩</button><button class="icon-btn" id="create-agent" title="Crear agente">＋</button><input class="hidden" id="agent-bundle-file" type="file" accept="application/json,.json"></div><div class="registry-list" id="agent-list"></div></aside><div class="agent-editor" id="agent-editor"></div></div></div>
    <div class="settings-tab-panel" id="settings-runtime"><div class="settings-form"><div class="notice">Los límites críticos del runtime siguen definidos en <span class="mono">sdd/pipeline.toml</span>. Los parámetros de inferencia y herramientas se administran por agente.</div><div class="stat-grid"><div class="stat"><span>Streaming</span><b>SSE · 500 ms</b></div><div class="stat"><span>Orquestación</span><b>LangGraph</b></div><div class="stat"><span>Persistencia</span><b>JSONL append-only</b></div><div class="stat"><span>Recuperación</span><b>Resume habilitado</b></div></div></div></div>
    <div class="settings-tab-panel" id="settings-security"><div class="settings-form"><div class="notice">Las claves permanecen en <span class="mono">config.json</span>, fuera de Git. Los prompts y resultados mostrados en el inspector deben considerarse datos sensibles del proyecto.</div></div></div>
  </div></div></section>
 </main>
</div>
<aside class="drawer" id="drawer" role="dialog" aria-modal="true" aria-label="Inspector de agente" aria-hidden="true" inert><div class="drawer-head"><div class="drawer-identity"><div class="agent-avatar" id="drawer-avatar">AI</div><div><b id="drawer-title">Agente</b><span id="drawer-subtitle">Sin selección</span></div></div><button class="icon-btn" id="drawer-close" aria-label="Cerrar inspector">×</button></div><div class="drawer-tabs" id="drawer-tabs"><button class="active" data-drawer="summary">Resumen</button><button data-drawer="trace">Traza</button><button data-drawer="logs">Logs</button><button data-drawer="io">I/O</button><button data-drawer="memory">Memoria</button></div><div class="drawer-body"><div class="drawer-panel active" id="drawer-summary"></div><div class="drawer-panel" id="drawer-trace"></div><div class="drawer-panel" id="drawer-logs"></div><div class="drawer-panel" id="drawer-io"></div><div class="drawer-panel" id="drawer-memory"></div></div></aside>
<div class="modal-backdrop" id="run-modal" role="dialog" aria-modal="true" aria-labelledby="run-modal-title" aria-hidden="true" inert><div class="modal"><div class="modal-head"><h2 id="run-modal-title">Nueva ejecución</h2><button class="icon-btn" data-close-modal="run-modal" aria-label="Cerrar nueva ejecución">×</button></div><div class="modal-body"><div class="field"><label for="idea">Objetivo</label><textarea id="idea" placeholder="Describe qué construir, criterios de aceptación y restricciones…"></textarea></div><div class="form-row"><div class="field"><label for="project">Proyecto</label><input id="project" placeholder="mi-proyecto"></div><div class="field"><label for="task">Ejecución</label><input id="task" placeholder="tarea-1"></div></div><section class="execution-profile" aria-labelledby="run-profile-title"><div><span id="run-profile-title">Entorno configurado</span><b id="run-profile">Cargando configuración…</b><small id="run-credential-status">Comprobando credencial</small></div><button class="ghost-btn" id="open-provider-settings" type="button">Cambiar en Configuración</button></section><label class="autonomy-option" for="autonomous"><input id="autonomous" type="checkbox" checked><span><b>Continuar sin revisiones manuales</b><small>Autoaprueba únicamente unidades que ya superaron sus gates. Los errores y límites de presupuesto siguen deteniendo la ejecución.</small></span></label><div class="path-preview" id="path-preview">project/mi-proyecto/tarea-1</div></div><div class="modal-foot"><button class="ghost-btn" data-close-modal="run-modal">Cancelar</button><button class="primary-btn" id="go"><span id="gotxt">Iniciar workflow</span></button></div></div></div>
<div class="modal-backdrop" id="create-modal" role="dialog" aria-modal="true" aria-labelledby="create-modal-title" aria-hidden="true" inert><div class="modal"><div class="modal-head"><h2 id="create-modal-title">Crear agente</h2><button class="icon-btn" data-close-modal="create-modal" aria-label="Cerrar creación de agente">×</button></div><div class="modal-body"><div class="form-row"><div class="field"><label for="new-agent-id">Identificador</label><input id="new-agent-id" placeholder="security_reviewer"></div><div class="field"><label for="new-agent-name">Nombre</label><input id="new-agent-name" placeholder="Security Reviewer"></div></div><div class="field"><label for="new-agent-role">Rol</label><input id="new-agent-role" placeholder="Revisa seguridad y amenazas"></div></div><div class="modal-foot"><button class="ghost-btn" data-close-modal="create-modal">Cancelar</button><button class="primary-btn" id="confirm-create-agent">Crear agente</button></div></div></div>
<div class="modal-backdrop" id="artifact-modal" role="dialog" aria-modal="true" aria-labelledby="artifact-title" aria-hidden="true" inert><div class="modal"><div class="modal-head"><h2 id="artifact-title">Artefacto</h2><button class="icon-btn" data-close-modal="artifact-modal" aria-label="Cerrar artefacto">×</button></div><div class="modal-body"><pre class="code-preview" id="artifact-content"></pre></div></div></div>
<button class="hidden" id=copylog aria-label="Copiar todo el registro"><span id="copylogtxt">Copiar todo</span></button><div class="toast" id="toast"></div>
<script>""" + SCRIPT + r"""</script></body></html>"""
