"""Comportamiento cliente de AutoScrum Control Tower."""
SCRIPT = r"""
const $=id=>document.getElementById(id);
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const slug=v=>(v||"").trim().replace(/[^A-Za-z0-9_.-]+/g,"-").replace(/^[-.]+|[-.]+$/g,"")||"sin-nombre";
const initials=v=>(v||"AI").split(/[\s_]+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const fmt=n=>new Intl.NumberFormat("es",{notation:Number(n)>9999?"compact":"standard"}).format(Number(n)||0);
let CFG={keys:{},agents:[],agent_profiles:{},custom_agents:[],model_choices:{}},STATE=null,LIVE_STATE=null;
let SOURCE="live",SELECTED_AGENT=null,SELECTED_ITERATION=null,eventSource=null,pollTimer=null,toastTimer=null;
const TOOL_OPTIONS=["filesystem","git","tests","gates","spec.read","spec.write","repository.inspect","tasks.plan","traceability","web"];
const STATE_LABEL={idle:"En reposo",thinking:"Pensando",tool_call:"Usando tool",streaming:"Transmitiendo",queued:"En cola",completed:"Completado",error:"Error",disabled:"Desactivado"};

function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),1800)}
function applyTheme(theme){if(theme==="auto")delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=theme}
function showView(name){qa(".view").forEach(v=>v.classList.toggle("hidden",v.id!=="view-"+name));qa(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===name));
 $("sidebar").classList.remove("open");const titles={workspace:["Vista en vivo",STATE?.project?`${STATE.project} · ${STATE.task}`:"Sin ejecución seleccionada"],history:["Historial","Ejecuciones persistidas"],results:["Resultados","Artefactos de la ejecución"],settings:["Configuración","Gobierno del sistema"]};
 const t=titles[name]||titles.workspace;$("crumb-title").textContent=t[0];$("crumb-sub").textContent=t[1];location.hash=name;if(name==="history")loadProjects();if(name==="results")renderGlobalResults()}
qa(".nav-btn").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("mobile-menu").onclick=()=>$("sidebar").classList.toggle("open");

function setCanvas(name){qa("#canvas-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.canvas===name));qa(".canvas-panel").forEach(p=>p.classList.toggle("active",p.id==="canvas-"+name));if(name==="topology")requestAnimationFrame(renderTopology)}
qa("#canvas-tabs button").forEach(b=>b.onclick=()=>setCanvas(b.dataset.canvas));
function setSettings(name){qa("#settings-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.settings===name));qa(".settings-tab-panel").forEach(p=>p.classList.toggle("active",p.id==="settings-"+name));if(name==="agents")renderAgentRegistry()}
qa("#settings-tabs button").forEach(b=>b.onclick=()=>setSettings(b.dataset.settings));
function setDrawerTab(name){qa("#drawer-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.drawer===name));qa(".drawer-panel").forEach(p=>p.classList.toggle("active",p.id==="drawer-"+name))}
qa("#drawer-tabs button").forEach(b=>b.onclick=()=>setDrawerTab(b.dataset.drawer));function closeDrawer(){const el=$("drawer");el.classList.remove("open");el.setAttribute("aria-hidden","true");el.setAttribute("inert","")}$("drawer-close").onclick=closeDrawer;
function closeModal(id){const el=$(id);el.classList.remove("open");el.setAttribute("aria-hidden","true");el.setAttribute("inert","")}qa("[data-close-modal]").forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));
function openModal(id){const el=$(id);el.classList.add("open");el.removeAttribute("inert");el.setAttribute("aria-hidden","false");setTimeout(()=>q("textarea,input,select,button",el)?.focus(),0)}

function statusKey(state){if(state?.status==="running")return"running";return state?.final||state?.status||"idle"}
function paintHeader(state){const key=statusKey(state),map={running:"Ejecutando",done:"Completado",completed:"Completado",escalated:"Escalado",waiting_human:"Revisión humana",idle:"En reposo"};
 const badge=$("run-state");badge.className="run-state "+(key==="running"?"running":key==="done"?"done":/error|escalated/.test(key)?"error":"");q("span",badge).textContent=map[key]||key;
 const active=(state.agents||[]).filter(a=>["thinking","tool_call","streaming"].includes(a.state)).length;$("metric-agents").textContent=`${active} activos`;$("nav-active").textContent=active;
 const tokens=(state.tokens?.input_tokens||0)+(state.tokens?.output_tokens||0);$("metric-tokens").textContent=fmt(tokens);$("crumb-sub").textContent=state.project?`${state.project} · ${state.task}`:"Sin ejecución seleccionada"}
function paint(state){STATE=state||{};paintHeader(STATE);paintLiveCard();paintIterations();paintStory();renderAgents();paintSprint(STATE.sprint||[]);renderResults();if(q("#canvas-topology.active"))requestAnimationFrame(renderTopology);if(SELECTED_AGENT)refreshDrawer()}
function paintLiveCard(){const running=STATE.status==="running";$("live-run-name").textContent=STATE.project?`${STATE.project} / ${STATE.task}`:"Sin ejecución activa";$("live-run-meta").textContent=STATE.project?`${running?"En ejecución":"Estado: "+(STATE.final||STATE.status)} · ${STATE.raw?.agent_calls||0} llamadas · ${(STATE.iterations||[]).length} iteraciones`:"Inicia un nuevo workflow para observarlo aquí.";q(".live-dot").style.background=running?"var(--cyan)":"var(--dim)"}
function paintIterations(){const list=STATE.iterations||[];$("iteration-count").textContent=list.length;$("iteration-list").innerHTML=list.length?list.map(it=>`<button class="iteration-item ${it.status} ${SELECTED_ITERATION===it.id?"active":""}" data-iteration="${it.id}"><span class="iteration-index">${String(it.index).padStart(2,"0")}</span><span class="iteration-copy"><b>${esc(it.node)}</b><span>${esc(it.task||"Iteración de pipeline")}</span></span><i class="iteration-status"></i></button>`).join(""):'<div class="empty-state"><b>Sin iteraciones</b>El hilo aparecerá al iniciar.</div>';
 qa("[data-iteration]").forEach(b=>b.onclick=()=>{SELECTED_ITERATION=b.dataset.iteration;paintIterations();paintStory()})}
function selectedIteration(){const list=STATE.iterations||[];return list.find(x=>x.id===SELECTED_ITERATION)||list[list.length-1]||null}
function paintStory(){const it=selectedIteration();$("workspace-title").textContent=STATE.project?`${STATE.project} · ${STATE.task}`:"Centro de operaciones";$("workspace-eyebrow").textContent=it?`Iteración ${String(it.index).padStart(2,"0")} · ${it.node}`:"Runtime multiagente";
 $("input-preview").textContent=STATE.input||"Aún no hay una ejecución seleccionada.";const running=STATE.status==="running";$("orchestrator-state").textContent=running?"ORQUESTANDO":STATE.final||"IDLE";$("topology-orch-state").textContent=running?"Orquestando":"En espera";q(".orchestrator-node")?.classList.toggle("active",running);
 $("orchestrator-copy").textContent=it?`Coordinando ${it.node}${it.task?" para "+it.task:""}. ${(it.gates||[]).length} gates evaluados y ${(it.defects||[]).length} defectos registrados.`:"Esperando una entrada para construir el plan de ejecución.";
 const arts=STATE.artifacts||[];$("result-summary").innerHTML=it?`<div class="stat-grid"><div class="stat"><span>Estado</span><b>${esc(it.status)}</b></div><div class="stat"><span>Gates</span><b>${(it.gates||[]).filter(g=>g[1]).length}/${(it.gates||[]).length}</b></div><div class="stat"><span>Defectos</span><b>${(it.defects||[]).length}</b></div><div class="stat"><span>Artefactos</span><b>${arts.length}</b></div></div>`:'<div class="empty-state"><b>Sin resultado</b>Los artefactos aparecerán al avanzar la ejecución.</div>'}

function renderAgents(){const agents=STATE.agents||CFG.agents||[];$("agent-matrix").innerHTML=agents.length?agents.map(agent=>`<button class="agent-card ${agent.state||"idle"}" data-agent="${esc(agent.id)}"><div class="agent-top"><div class="agent-avatar">${initials(agent.name)}</div><div class="agent-copy"><b>${esc(agent.name||agent.id)}</b><span>${esc(agent.current_task||agent.role||"")}</span></div><span class="state-label">${esc(STATE_LABEL[agent.state]||agent.state||"idle")}</span></div><div class="agent-meta"><span>${agent.tasks_done||0}/${agent.tasks||0} tareas</span><span>${(agent.tools||[]).length} tools</span></div></button>`).join(""):'<div class="empty-state"><b>Sin agentes</b>Configura el catálogo de agentes.</div>';qa("[data-agent]").forEach(b=>b.onclick=()=>openAgent(b.dataset.agent))}
function paintSprint(tasks){const el=$("subtask-list");el.innerHTML=tasks.length?tasks.map(t=>`<button class="subtask-row ${esc(t.status||"pending")}" data-task-id="${esc(t.id)}"><i></i><b>${esc(t.id)}</b><span>${esc(t.title||t.node||"")}</span><em>${esc(t.status||"pending")}</em></button>`).join(""):'<div class="empty-state"><b>Sin subtareas</b>El plan se desplegará aquí.</div>';qa("[data-task-id]").forEach(b=>b.onclick=()=>openTaskTrace(b.dataset.taskId))}
function renderTopology(){const box=$("topology");if(!box||box.clientWidth<20)return;qa(".topology-node",box).forEach(n=>n.remove());const svg=$("topology-edges"),agents=STATE.agents||CFG.agents||[],w=box.clientWidth,h=box.clientHeight,cx=w/2,cy=h/2,rx=Math.max(190,Math.min(w*.36,430)),ry=Math.max(170,Math.min(h*.36,280));let lines="";
 agents.forEach((a,i)=>{const angle=-Math.PI/2+(Math.PI*2*i/Math.max(agents.length,1)),x=cx+Math.cos(angle)*rx,y=cy+Math.sin(angle)*ry,node=document.createElement("button");node.className=`topology-node ${a.state||"idle"}`;node.dataset.agent=a.id;node.style.left=x+"px";node.style.top=y+"px";node.innerHTML=`<b>${esc(a.name||a.id)}</b><span>${esc(a.current_task||a.role||"")}</span><span class="node-state">${esc(STATE_LABEL[a.state]||a.state||"idle")}</span>`;node.onclick=()=>openAgent(a.id);box.appendChild(node);lines+=`<line class="edge ${["thinking","tool_call","streaming"].includes(a.state)?"active":""}" x1="${cx}" y1="${cy}" x2="${x}" y2="${y}"/>`});svg.innerHTML=lines}
window.addEventListener("resize",()=>q("#canvas-topology.active")&&renderTopology());

function renderResults(target="results-grid"){const el=$(target),items=STATE?.artifacts||[];if(!el)return;el.innerHTML=items.length?items.map(a=>`<button class="artifact-card" data-artifact="${esc(a.path)}"><b>${esc(a.path)}</b><span>${fmt(a.size)} bytes · actualizado ${new Date(a.updated*1000).toLocaleString()}</span></button>`).join(""):'<div class="empty-state"><b>Sin artefactos disponibles</b>Selecciona una ejecución con resultados.</div>';qa("[data-artifact]",el).forEach(b=>b.onclick=()=>openArtifact(b.dataset.artifact))}
function renderGlobalResults(){renderResults("global-results")}
async function openArtifact(path){if(!STATE?.project)return;$("artifact-title").textContent=path;$("artifact-content").textContent="Cargando…";openModal("artifact-modal");const url=`/artifact?project=${encodeURIComponent(STATE.project)}&task=${encodeURIComponent(STATE.task)}&path=${encodeURIComponent(path)}`;const r=await fetch(url);$("artifact-content").textContent=await r.text()}

function findAgent(id){return (STATE?.agents||[]).find(a=>a.id===id)||(CFG.agents||[]).find(a=>a.id===id)}
function openAgent(id){SELECTED_AGENT=id;setDrawerTab("summary");const el=$("drawer");el.classList.add("open");el.removeAttribute("inert");el.setAttribute("aria-hidden","false");refreshDrawer(true);setTimeout(()=>$("drawer-close").focus(),0)}
function agentDefinition(id){return (CFG.agents||[]).find(a=>a.id===id)||{}}
function refreshDrawer(loadTrace=false){const agent=findAgent(SELECTED_AGENT);if(!agent)return;const def=agentDefinition(agent.id);$("drawer-avatar").textContent=initials(agent.name);$("drawer-title").textContent=agent.name||agent.id;$("drawer-subtitle").textContent=`${agent.role||def.role||"Agente"} · ${STATE_LABEL[agent.state]||agent.state||"idle"}`;
 $("drawer-summary").innerHTML=`<div class="stat-grid"><div class="stat"><span>Estado</span><b>${esc(STATE_LABEL[agent.state]||agent.state||"idle")}</b></div><div class="stat"><span>Tareas</span><b>${agent.tasks_done||0}/${agent.tasks||0}</b></div><div class="stat"><span>Modelo</span><b>${esc(agent.model||def.model||"Global")}</b></div><div class="stat"><span>Herramientas</span><b>${(agent.tools||def.tools||[]).length}</b></div></div><div class="tag-row" style="margin-top:12px">${(agent.tools||def.tools||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join("")}</div>`;
 renderAgentLogs(agent.id);$("drawer-io").innerHTML=`<div class="eyebrow">Prompt base · ${esc(def.prompt_path||"custom")}</div><pre class="code-preview">${esc(def.prompt_base||"Sin prompt base")}</pre><div class="eyebrow" style="margin-top:14px">Complemento del operador</div><pre class="code-preview">${esc(def.prompt_addon||"Sin instrucciones adicionales")}</pre>`;$("drawer-memory").innerHTML='<div class="empty-state"><b>Sin eventos de memoria</b>El runtime actual no emite snapshots de memoria estructurados. Esta vista se activará cuando existan eventos memory.read y memory.write.</div>';
 if(loadTrace){const taskId=agent.current_task||[...(STATE.sprint||[])].reverse().find(t=>t.node===agent.id)?.id;if(taskId)fetchTrace(STATE.project,STATE.task,taskId);else $("drawer-trace").innerHTML='<div class="empty-state"><b>Sin traza</b>Este agente todavía no tiene una tarea ejecutada.</div>'}}
function renderAgentLogs(id){const lines=(STATE.log||[]).filter(line=>line.includes(id)||!id);$("drawer-logs").innerHTML=`<div class="log-toolbar"><input id="log-filter" placeholder="Filtrar logs…"><select id="log-level"><option value="all">Todos</option><option value="error">Error</option><option value="warn">Warning</option><option value="info">Info</option></select><button class="ghost-btn" id="drawer-copy-log">Copiar</button></div><div class="log-stream" id="log-stream"></div>`;const paintLogs=()=>{const term=$("log-filter").value.toLowerCase(),level=$("log-level").value;$("log-stream").innerHTML=lines.filter(l=>(!term||l.toLowerCase().includes(term))&&(level==="all"||logClass(l)===level)).map(l=>`<span class="log-line ${logClass(l)}">${esc(l)}</span>`).join("")||'<span class="dim">Sin eventos coincidentes.</span>';$("log-stream").scrollTop=$("log-stream").scrollHeight};$("log-filter").oninput=paintLogs;$("log-level").onchange=paintLogs;$("drawer-copy-log").onclick=()=>copyText(lines.join("\n"));paintLogs()}
function logClass(line){if(/error|defecto|escalate|fallo/i.test(line))return"error";if(/reintento|revert|omitido|warning/i.test(line))return"warn";if(/aprobado|done|escrito|integrated/i.test(line))return"ok";if(/gate|agente|nodo/i.test(line))return"info";return""}
function openTaskTrace(taskId){const task=(STATE.sprint||[]).find(t=>t.id===taskId),agent=task?findAgent(task.node):null;SELECTED_AGENT=agent?.id||task?.node||"task";const drawer=$("drawer");drawer.classList.add("open");drawer.removeAttribute("inert");drawer.setAttribute("aria-hidden","false");$("drawer-title").textContent=taskId;$("drawer-subtitle").textContent=task?.title||task?.node||"Traza de tarea";setDrawerTab("trace");fetchTrace(STATE.project,STATE.task,taskId);setTimeout(()=>$("drawer-close").focus(),0)}
async function fetchTrace(project,task,tid){const body=$("drawer-trace");body.innerHTML='<div class="empty-state"><b>Cargando traza</b>Consultando el journal de ciclo de vida…</div>';try{const r=await fetch(`/lifecycle?project=${encodeURIComponent(project||"")}&task=${encodeURIComponent(task||"")}&task_id=${encodeURIComponent(tid)}`),data=await r.json(),events=data.events||[],summary=data.summary||{},tokens=data.tokens||{};body.innerHTML=`<div class="stat-grid"><div class="stat"><span>Estado</span><b>${esc(summary.status||"?")}</b></div><div class="stat"><span>Eventos</span><b>${events.length}</b></div><div class="stat"><span>Llamadas</span><b>${summary.calls||0}</b></div><div class="stat"><span>Tokens</span><b>${fmt((tokens.input_tokens||0)+(tokens.output_tokens||0))}</b></div></div><div class="trace-list" style="margin-top:12px">${events.map(ev=>{const fail=ev.status==="fail"||["blocked","escalated"].includes(ev.event);return `<div class="trace-row ${fail?"fail":["done","integrated"].includes(ev.event)?"ok":""}"><b>${esc(ev.event||"evento")}</b><span>${esc(traceDetail(ev))} · ${esc((ev.t||"").slice(11,23))}</span></div>`}).join("")}</div>`}catch(e){body.innerHTML=`<div class="empty-state"><b>No se pudo cargar</b>${esc(e.message)}</div>`}}
function traceDetail(ev){if(ev.event==="gate_result")return `${ev.gate} · ${ev.status} · ${ev.findings||0} hallazgos`;if(ev.event==="blocked")return `Bloqueado por ${ev.blocked_by||"dependencia"}`;if(ev.event==="agent_called")return `returncode ${ev.returncode}`;return ev.detail||ev.reason||ev.node||"evento registrado"}

async function loadCfg(){const c=await fetch("/config").then(r=>r.json());CFG={...c,keys:c.keys||{},agents:c.agents||[],agent_profiles:c.agent_profiles||{},custom_agents:c.custom_agents||[],model_choices:c.model_choices||{}};$("output-base").value=CFG.output_base||"project";$("theme").value=CFG.theme||"auto";applyTheme(CFG.theme||"auto");$("provider").value=CFG.provider||"anthropic";fillModels("provider-model",$("provider").value,CFG.model);$("provider-key").value=CFG.keys[$("provider").value]||"";renderAgentRegistry();syncRunForm()}
function fillModels(id,provider,selected){const el=$(id),models=CFG.model_choices?.[provider]||[];el.innerHTML=(models.length?models:[""]).map(m=>`<option value="${esc(m)}">${esc(m||"Modelo definido por entorno")}</option>`).join("");if(selected&&models.includes(selected))el.value=selected}
function syncRunForm(){const provider=CFG.provider||"anthropic";$("run-provider").value=provider;fillModels("model",provider,CFG.model);$("run-key").value="";pathPreview()}
$("provider").onchange=()=>{fillModels("provider-model",$("provider").value,"");$("provider-key").value=CFG.keys[$("provider").value]||""};$("run-provider").onchange=()=>fillModels("model",$("run-provider").value,"");
$("theme").onchange=()=>applyTheme($("theme").value);$("toggle-key").onclick=()=>$("provider-key").type=$("provider-key").type==="password"?"text":"password";
async function saveConfig(patch){const c=await fetch("/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}).then(r=>r.json());CFG={...CFG,...c};return c}
$("save-general").onclick=async()=>{await saveConfig({output_base:$("output-base").value,theme:$("theme").value});saved("saved-general")};
$("save-provider").onclick=async()=>{const p=$("provider").value,key=$("provider-key").value;await saveConfig({provider:p,model:$("provider-model").value,keys:{[p]:key}});CFG.keys[p]=key;saved("saved-provider")};
function saved(id){$(id).classList.add("show");setTimeout(()=>$(id).classList.remove("show"),1600)}

function renderAgentRegistry(){const term=($("agent-search")?.value||"").toLowerCase(),agents=(CFG.agents||[]).filter(a=>!term||`${a.name} ${a.id} ${a.role}`.toLowerCase().includes(term));$("agent-list").innerHTML=agents.map(a=>`<div class="registry-item ${SELECTED_AGENT===a.id?"active":""}" data-edit-agent="${esc(a.id)}"><div class="agent-avatar">${initials(a.name)}</div><div><b>${esc(a.name)}</b><span>${esc(a.id)} · ${esc(a.model||"modelo global")}</span></div><button class="switch ${a.enabled!==false?"on":""}" data-toggle-agent="${esc(a.id)}" aria-label="Activar o desactivar ${esc(a.name)}"><i></i></button></div>`).join("");qa("[data-edit-agent]").forEach(el=>el.onclick=e=>{if(e.target.closest("[data-toggle-agent]"))return;SELECTED_AGENT=el.dataset.editAgent;renderAgentRegistry();renderAgentEditor()});qa("[data-toggle-agent]").forEach(b=>b.onclick=async e=>{e.stopPropagation();const a=agentDefinition(b.dataset.toggleAgent);await persistAgent(a,{enabled:a.enabled===false});toast(a.enabled===false?"Agente activado":"Agente desactivado")});if(!SELECTED_AGENT&&agents[0])SELECTED_AGENT=agents[0].id;renderAgentEditor()}
$("agent-search").oninput=renderAgentRegistry;
function renderAgentEditor(){const a=agentDefinition(SELECTED_AGENT),root=$("agent-editor");if(!a.id){root.innerHTML='<div class="empty-state"><b>Selecciona un agente</b>Configura prompts, modelo y herramientas.</div>';return}const tools=[...new Set([...TOOL_OPTIONS,...(a.tools||[])])];root.innerHTML=`<div class="editor-head"><div><h3>${esc(a.name)}</h3><p>${esc(a.id)} · ${a.built_in?"Agente del pipeline":"Agente personalizado"}</p></div><button class="primary-btn" id="save-agent">Guardar agente</button></div><div class="editor-tabs"><button class="active" data-editor="general">General</button><button data-editor="model">Modelo</button><button data-editor="prompt">Prompt</button><button data-editor="tools">Herramientas</button><button data-editor="runtime">Runtime</button></div>
 <div class="editor-panel active" id="editor-general"><div class="form-row"><div class="field"><label>Identificador</label><input id="agent-id" value="${esc(a.id)}" disabled></div><div class="field"><label>Estado</label><select id="agent-enabled"><option value="true" ${a.enabled!==false?"selected":""}>Activo</option><option value="false" ${a.enabled===false?"selected":""}>Desactivado</option></select></div></div><div class="form-row"><div class="field"><label>Nombre</label><input id="agent-name" value="${esc(a.name)}" ${a.built_in?"disabled":""}></div><div class="field"><label>Rol</label><input id="agent-role" value="${esc(a.role)}" ${a.built_in?"disabled":""}></div></div></div>
 <div class="editor-panel" id="editor-model"><div class="form-row"><div class="field"><label>Proveedor</label><select id="agent-provider"><option value="">Heredar global</option>${Object.keys(CFG.model_choices||{}).map(p=>`<option value="${p}" ${a.provider===p?"selected":""}>${p}</option>`).join("")}</select></div><div class="field"><label>Modelo</label><input id="agent-model" value="${esc(a.model||"")}" placeholder="Heredar del proveedor"></div></div><div class="form-row"><div class="field"><label>Temperatura · <span id="temp-value">${Number(a.temperature??.2).toFixed(1)}</span></label><input id="agent-temperature" type="range" min="0" max="2" step="0.1" value="${a.temperature??.2}"></div><div class="field"><label>Tokens máximos · 0 hereda</label><input id="agent-max-tokens" type="number" min="0" max="200000" value="${a.max_tokens||0}"></div></div></div>
 <div class="editor-panel" id="editor-prompt"><div class="field"><label>Complemento del operador</label><textarea id="agent-addon" placeholder="Instrucciones adicionales…">${esc(a.prompt_addon||"")}</textarea></div><div class="field"><label>Prompt base · solo lectura</label><pre class="code-preview base-prompt">${esc(a.prompt_base||"Sin prompt base")}</pre></div></div>
 <div class="editor-panel" id="editor-tools"><div class="tool-grid">${tools.map(t=>`<label class="tool-option"><input type="checkbox" data-tool="${esc(t)}" ${(a.tools||[]).includes(t)?"checked":""}>${esc(t)}</label>`).join("")}</div></div>
 <div class="editor-panel" id="editor-runtime"><div class="notice">Permisos de escritura y gates provienen del pipeline. Desactivar el agente hace que una invocación futura se declare bloqueada y escale de forma visible.</div><div class="field"><label>Rutas permitidas</label><div class="tag-row">${(a.writes||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join("")||'<span class="dim">Sin rutas declaradas</span>'}</div></div><div class="field"><label>Gates</label><div class="tag-row">${(a.gates||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join("")||'<span class="dim">Sin gates</span>'}</div></div></div>`;
 qa("[data-editor]",root).forEach(b=>b.onclick=()=>{qa("[data-editor]",root).forEach(x=>x.classList.toggle("active",x===b));qa(".editor-panel",root).forEach(p=>p.classList.toggle("active",p.id==="editor-"+b.dataset.editor))});$("agent-temperature").oninput=()=>$("temp-value").textContent=Number($("agent-temperature").value).toFixed(1);$("save-agent").onclick=saveAgentEditor}
async function saveAgentEditor(){const a=agentDefinition(SELECTED_AGENT),patch={enabled:$("agent-enabled").value==="true",provider:$("agent-provider").value,model:$("agent-model").value,temperature:Number($("agent-temperature").value),max_tokens:Number($("agent-max-tokens").value)||0,prompt_addon:$("agent-addon").value,tools:qa("[data-tool]:checked").map(x=>x.dataset.tool)};if(!a.built_in){a.name=$("agent-name").value;a.role=$("agent-role").value}await persistAgent(a,patch);toast("Agente guardado")}
async function persistAgent(agent,patch){Object.assign(agent,patch);const profiles={[agent.id]:{enabled:agent.enabled,provider:agent.provider||"",model:agent.model||"",temperature:agent.temperature??.2,max_tokens:agent.max_tokens||0,prompt_addon:agent.prompt_addon||"",tools:agent.tools||[]}};let custom=CFG.custom_agents||[];if(!agent.built_in)custom=custom.map(x=>x.id===agent.id?{...x,name:agent.name,role:agent.role,prompt_base:agent.prompt_base||"",writes:agent.writes||[],gates:agent.gates||[]}:x);await saveConfig({agent_profiles:profiles,custom_agents:custom});await loadCfg();SELECTED_AGENT=agent.id;renderAgentRegistry()}
$("create-agent").onclick=()=>openModal("create-modal");$("confirm-create-agent").onclick=async()=>{const id=slug($("new-agent-id").value),name=$("new-agent-name").value.trim()||id,role=$("new-agent-role").value.trim()||"Custom agent";if(!id||id==="sin-nombre"){toast("Define un identificador");return}if((CFG.agents||[]).some(a=>a.id===id)){toast("Ese agente ya existe");return}const custom=[...(CFG.custom_agents||[]),{id,name,role,prompt_base:"",writes:[],gates:[]}];await saveConfig({custom_agents:custom,agent_profiles:{[id]:{enabled:true,temperature:.2,max_tokens:0,prompt_addon:"",tools:["filesystem"]}}});closeModal("create-modal");SELECTED_AGENT=id;await loadCfg();renderAgentRegistry();toast("Agente creado")};

async function loadProjects(){const list=await fetch("/projects").then(r=>r.json()),sel=$("history-project"),cur=sel.value;sel.innerHTML=list.length?list.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join(""):'<option value="">Sin proyectos</option>';if(list.includes(cur))sel.value=cur;await loadTasks()}
async function loadTasks(){const project=$("history-project").value;if(!project){$("history-tasks").innerHTML='<div class="empty-state"><b>Sin proyectos</b>Inicia una ejecución.</div>';return}const list=await fetch(`/tasks?project=${encodeURIComponent(project)}`).then(r=>r.json());$("history-tasks").innerHTML=list.map(t=>{const pct=Math.round(100*t.done/Math.max(t.total,1)),resume=["escalated","waiting_human","running"].includes(t.final);return `<article class="task-card" data-history-task="${esc(t.task)}"><div class="task-card-head"><b>${esc(t.task)}</b><span class="status-pill ${esc(t.final)}">${esc(t.final)}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="task-meta">${t.done}/${t.total} ${esc(t.unit||"nodos")} · ${t.calls} llamadas</div>${resume?`<button class="ghost-btn" data-resume="${esc(t.task)}" style="margin-top:12px">Continuar</button>`:""}</article>`}).join("")||'<div class="empty-state"><b>Sin ejecuciones</b>Este proyecto aún no tiene runs.</div>';qa("[data-history-task]").forEach(card=>card.onclick=e=>{if(e.target.closest("[data-resume]"))return;viewTask(project,card.dataset.historyTask)});qa("[data-resume]").forEach(b=>b.onclick=()=>resumeTask(project,b.dataset.resume))}
$("history-project").onchange=loadTasks;$("refresh-history").onclick=loadProjects;
async function viewTask(project,task){SOURCE="history";const data=await fetch(`/task?project=${encodeURIComponent(project)}&task=${encodeURIComponent(task)}`).then(r=>r.json());SELECTED_ITERATION=null;paint(data);showView("workspace")}
async function resumeTask(project,task){const r=await fetch("/resume",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project,task})}),data=await r.json();if(!r.ok){toast(data.error||"No se pudo continuar");return}SOURCE="live";showView("workspace");fetchState();toast("Ejecución reanudada")}

function pathPreview(){if(!$("project"))return;$("path-preview").textContent=`${$("output-base").value||CFG.output_base||"project"}/${slug($("project").value)}/${slug($("task").value||"tarea-1")}`}
["project","task"].forEach(id=>$(id).oninput=pathPreview);["new-run","new-run-rail"].forEach(id=>$(id).onclick=()=>{syncRunForm();openModal("run-modal")});
$("go").onclick=async()=>{const project=$("project").value.trim(),idea=$("idea").value.trim(),provider=$("run-provider").value,key=$("run-key").value||CFG.keys[provider]||"";if(!project){toast("Define el proyecto");return}if(!idea){toast("Describe el objetivo");return}if(!key){toast("Configura la API key del proveedor");return}const button=$("go");button.disabled=true;$("gotxt").textContent="Iniciando…";try{const r=await fetch("/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,provider,model:$("model").value,key,project,task:$("task").value})}),data=await r.json();if(!r.ok)throw new Error(data.error||"No se pudo iniciar");closeModal("run-modal");SOURCE="live";SELECTED_ITERATION=null;showView("workspace");await fetchState();toast("Workflow iniciado")}catch(e){toast(e.message)}finally{button.disabled=false;$("gotxt").textContent="Iniciar workflow"}};
function stopBtn(){$("go").disabled=false;$("gotxt").textContent="Iniciar workflow"}

function connection(live,text){const el=$("connection");el.classList.toggle("live",live);q("span",el).textContent=text}
async function fetchState(){try{const state=await fetch("/state").then(r=>r.json());LIVE_STATE=state;if(SOURCE==="live")paint(state);connection(true,"Runtime conectado")}catch(_){connection(false,"Runtime no disponible")}}
function connectStream(){if(!window.EventSource){pollTimer=setInterval(fetchState,1000);fetchState();return}eventSource=new EventSource("/events");eventSource.addEventListener("state",event=>{try{LIVE_STATE=JSON.parse(event.data);if(SOURCE==="live")paint(LIVE_STATE);connection(true,"Actualización en vivo")}catch(_){}});eventSource.onopen=()=>connection(true,"Actualización en vivo");eventSource.onerror=()=>connection(false,"Reconectando…")}
$("live-run-card").onclick=()=>{SOURCE="live";SELECTED_ITERATION=null;if(LIVE_STATE)paint(LIVE_STATE);showView("workspace")};
function legacyCopy(text){const a=document.createElement("textarea");a.value=text;a.setAttribute("readonly","");a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();try{return document.execCommand("copy")}finally{a.remove()}}
async function copyText(text){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else if(!legacyCopy(text))throw new Error("copy");toast("Copiado al portapapeles")}catch(_){toast("No se pudo copiar")}}
async function copyLog(){const LOG_LINES=STATE?.log||[];return copyText(LOG_LINES.join("\n"))}$("copylog").onclick=copyLog;

(async function init(){await loadCfg();fetch("/idea").then(r=>r.text()).then(t=>{if(t&&!$("idea").value)$("idea").value=t});await fetchState();connectStream();const initial=(location.hash||"#workspace").slice(1);showView(["workspace","history","results","settings"].includes(initial)?initial:"workspace")})();
"""